import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'
import styles from '../styles/Home.module.css'

export default function Home({ exploreData, cardsData }) {
  return (
    <div className=''>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className='max-w-7xl mx-auto sm:px-16 p-2'>
        <section className='mt-5'>
          <h2 className='text-4xl font-semibold mb-5'>Explore Nearby</h2>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4'>
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                img={img}
                location={location}
                distance={distance}
                key={location}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G")
    .then((res) => res.json());
  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT")
    .then((res) => res.json());
  return {
    props: {
      exploreData,
      cardsData
    }
  }
}
